version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: registry:2
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: setup dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
            git config --global user.email "ci@circleci"
            git config --global user.name "ci"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            mkdir -p test-reports/unit
            # Use local docker registry for our unit tests
            export DOCKER_REGISTRY=localhost:5000
            py.test --junitxml=test-reports/unit/results.xml tests/

      - store_test_results:
          path: test-reports
