version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-3.7.0-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-3.7.0-

      - run:
          name: setup dependencies
          command: |
            pyenv global 3.7.0
            python3 -m venv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
            git config --global user.email "ci@circleci"
            git config --global user.name "ci"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-3.7.0-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            mkdir -p test-reports/unit
            py.test --cov=hubploy --junitxml=test-reports/unit/results.xml tests/

      - run:
          name: upload coverage info to codecov
          command: |
            source venv/bin/activate
            codecov

      - store_test_results:
          path: test-reports
